name: Playwright Tests
on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright Browsers
      run: npx playwright install chromium --with-deps

    - name: Run E2E Tests
      run: npm run uitest_uat

    - name: Run API Tests
      run: npm run apitest

    - name: Run DB Tests
      run: npm run dbtest

    - name: Load environment variables from .env file
      run: |
        export $(cat .env | xargs) 

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: ortoni-report/
        retention-days: 30
